import { run } from "../core/exec.js";
import { requireRuntimeAgreement } from "../core/runtime-agreement.js";
import { runtimeIdentity } from "../core/version.js";
import { readInstallState } from "../harness/install-state.js";
import type { WorkspaceState } from "../workflow/state.js";
import type { Check } from "./checks.js";

/** Diagnosis remains available when installed provenance cannot authorize writes. */
export async function checkInstalledRuntime(state: WorkspaceState): Promise<Check> {
  const name = "installed runtime";
  const recovery =
    "Choose the intended VISP build, run visp install to refresh project assets, and restart stale MCP/host processes.";
  const installed = await readInstallState(state.paths, state.files);
  if (!installed.ok) return { name, status: "fail", detail: installed.error.message, recovery };
  const runtime = installed.value?.runtime;
  if (!runtime)
    return {
      name,
      status: "warn",
      detail:
        "No identified installation runtime; product mutations require refreshed installation assets",
      recovery,
    };
  const agreed = requireRuntimeAgreement(runtime);
  if (!agreed.ok) return { name, status: "fail", detail: agreed.error.message, recovery };
  return {
    name,
    status: "ok",
    detail: `Installed assets generated by VISP ${runtime.version} build ${runtime.buildId} (${runtime.executable})`,
  };
}

/** An MCP server and the `visp` found by shell tools may be different builds. */
export async function checkPathRuntime(state: WorkspaceState): Promise<Check> {
  const name = "PATH runtime";
  const checked = await run("visp", ["doctor", "--runtime-identity", "--json"], {
    cwd: state.paths.root,
    timeoutMs: 5000,
  });
  if (!checked.ok || checked.value.exitCode !== 0)
    return { name, status: "warn", detail: "Could not identify the visp executable on PATH" };
  try {
    const parsed = JSON.parse(checked.value.stdout) as {
      data?: { runtime?: { buildId?: string } };
    };
    const found = parsed.data?.runtime?.buildId;
    if (found === runtimeIdentity().buildId)
      return { name, status: "ok", detail: `PATH uses build ${found}` };
    return {
      name,
      status: "fail",
      detail: `PATH visp build ${found ?? "unknown"} differs from this runtime ${runtimeIdentity().buildId}`,
      recovery: "Use the same VISP build for MCP and CLI, then restart the MCP server",
    };
  } catch {
    return { name, status: "warn", detail: "PATH visp returned an unrecognized runtime identity" };
  }
}
