import { requireRuntimeAgreement } from "../core/runtime-agreement.js";
import { readInstallState } from "../harness/install-state.js";
import type { WorkspaceState } from "../workflow/state.js";
import type { Check } from "./checks.js";

/** Diagnosis remains available when installed provenance cannot authorize writes. */
export async function checkInstalledRuntime(state: WorkspaceState): Promise<Check> {
  const name = "installed runtime";
  const recovery =
    "Choose the intended VISP build, run visp install to refresh project assets, and restart stale MCP/host processes.";
  const installed = await readInstallState(state.paths, state.files);
  if (!installed.ok) return { name, status: "fail", detail: installed.error.message, recovery };
  const runtime = installed.value?.runtime;
  if (!runtime)
    return {
      name,
      status: "warn",
      detail:
        "No identified installation runtime; product mutations require refreshed installation assets",
      recovery,
    };
  const agreed = requireRuntimeAgreement(runtime);
  if (!agreed.ok) return { name, status: "fail", detail: agreed.error.message, recovery };
  return {
    name,
    status: "ok",
    detail: `Installed assets generated by VISP ${runtime.version} build ${runtime.buildId} (${runtime.executable})`,
  };
}
